source 'https://rubygems.org'

gem 'activerecord',  '~>4.2.2'
gem 'activesupport', '~>4.2.2'
gem 'httparty',      '~>0.13.0'
gem 'json',          '~>1.8.1'
gem 'sanitize',      '~>2.1.0'
gem 'twitter',       '~>5.9.0'
gem 'rspec',         '~>3.3.0'
gem 'rspec-its',     '~>1.2.0'
gem 'rake',          '~>10.3.1'
gem 'sqlite3',       '~>1.3.9'
